### ISSUE TITLE
Problem with 1.0.*@dev

### ISSUE THREAD

**Issue by adridev** [dflydev/dflydev-doctrine-orm-service-provider#40]
This is the stacktrace: 

```
/mnt/workspace/bitbucket/qnoow/brain/vendor/pimple/pimple/lib/Pimple.php 78 Identifier "default" is not defined.
#0 /mnt/workspace/bitbucket/qnoow/brain/vendor/dflydev/doctrine-orm-service-provider/src/Dflydev/Pimple/Provider/DoctrineOrm/DoctrineOrmServiceProvider.php(107): Pimple->offsetGet('default')
#1 /mnt/workspace/bitbucket/qnoow/brain/vendor/pimple/pimple/lib/Pimple.php(126): Dflydev\Pimple\Provider\DoctrineOrm\DoctrineOrmServiceProvider->Dflydev\Pimple\Provider\DoctrineOrm\{closure}(Object(Pimple))
...
```

 Setting required version to @stable fixed the issue. May be an config issue?

**Comment by MarcosSegovia** [comment]
got the same problem and could not resolved even though changing the version.
